# Generated by Django 5.0.4 on 2024-04-16 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(choices=[('AP', 'Apple'), ('SM', 'Samsung'), ('GO', 'Google'), ('SO', 'Sony'), ('XI', 'Xiaomi'), ('HU', 'Huawei')], max_length=2)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('Schwarz', 'Schwarz'), ('Weiß', 'Weiß'), ('Rot', 'Rot'), ('Blau', 'Blau'), ('Grün', 'Grün'), ('Gelb', 'Gelb'), ('Grau', 'Grau'), ('Silber', 'Silber'), ('Gold', 'Gold')], default='Schwarz', max_length=10)),
                ('memory_size', models.CharField(choices=[('6', '6 GB'), ('8', '8 GB'), ('12', '12 GB'), ('16', '16 GB')], default='8', max_length=2)),
                ('storage_size', models.CharField(choices=[('128', '128 GB'), ('256', '256 GB'), ('512', '512 GB'), ('1024', '1 TB')], default='128', max_length=4)),
                ('akku', models.IntegerField()),
                ('camera', models.TextField()),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('costumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=150)),
                ('house_number', models.CharField(max_length=10)),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.costumer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('D', 'Dispatched'), ('F', 'Finished')], default='P', max_length=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.address')),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.costumer')),
                ('products', models.ManyToManyField(to='shop.cartitem')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='smartphone',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.smartphone'),
        ),
    ]
