# Generated by Django 5.0.4 on 2024-04-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='picture',
            new_name='picture01',
        ),
        migrations.RemoveField(
            model_name='smartphone',
            name='camera',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='cores',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='display',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='front_camera',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='ghz',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='main_camera',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='picture02',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='picture03',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='picture04',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='prozessortyp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='basic_price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
