# Generated by Django 5.0.4 on 2024-04-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_costumer_costumer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='costumer',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='costumer',
            new_name='user',
        ),
    ]
