# Generated by Django 5.0.4 on 2024-04-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_user_address_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartphone',
            old_name='picture01',
            new_name='pictureBack',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='picture02',
            new_name='pictureDetail',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='picture03',
            new_name='pictureFront',
        ),
        migrations.RenameField(
            model_name='smartphone',
            old_name='picture04',
            new_name='pictureSide',
        ),
    ]
